fix references from Cargo.lock to Cargo.toml
neilwashere/rust-project-root pull request #18
Opened 2021-08-16 23:40 UTC by joseluis

it should look for Cargo.toml since Cargo.lock is not always present

2023-01-09 00:50 UTC, jayvdb requested changes
This will radically change what "project root" means ; c.f. https://stackoverflow.com/questions/75052086/how-to-locate-the-cargo-lock-from-build-rs

2023-01-10 16:05 UTC, joseluis commented
@jayvdb Ok I think I get what you mean. I was assumming the word project meant crate or package, but the term seems to be overloaded to also mean workspace. Both Cargo.toml and Cargo.lock will be present in the package's root, but there's going to be only one shared Cargo.lock at the workspace's root.

So searching the Cargo.toml would give the closest package's root. And searching for a Cargo.lock will give the closest project's root (which will be either the closest crate or its parent's workspace).

I'm going to close this PR. I also made a different version for finding the current's crate root, supporting path suffixes: [devela::crate_root](https://docs.rs/devela/latest/devela/fn.crate_root.html).

2023-01-10 16:05 UTC, closed without merging

2023-01-25 07:40 UTC, jayvdb commented
Note there is a similar crate which finds the Cargo.toml https://github.com/spazm/find-cargo-toml but it isnt on crates.io

2023-01-25 07:42 UTC, jayvdb commented
https://docs.rs/devela/latest/devela/fn.crate_root.html says its repo is https://github.com/andamira/devela , but that repo isnt public.

2023-01-25 07:47 UTC, jayvdb commented
https://github.com/andamira/libera/blob/main/src/project.rs has a similar 'find Cargo.toml' routine.

2023-01-25 10:40 UTC, joseluis commented
> repo isnt public.

ops! fixed! thank you

2023-01-27 09:35 UTC, jayvdb commented
note https://github.com/neilwashere/rust-project-root/pull/20 allows using this crate to achieve the same as this PR.